### ISSUE TITLE
Can't edit files after running cookiecutter

### ISSUE THREAD

**Issue by larmitage-bjss** [andrewthetechie/gha-cookiecutter#40]
**Describe the bug**

After I run the github action to create my new folder using cookiecutter, I want to edit the file but the github runner does not have permissions to do so as the files are created as root.

(The reason to write to the file is that I need to add new lines to correctly format my terraform file after inserting a variable and new lines are not allowed in variables)

**To Reproduce**

Here are my github action steps:
```yaml
      - name: Run Cookiecutter
        id: cookiecutter
        uses: andrewthetechie/gha-cookiecutter@v1
        with:
          template: templates/${{ inputs.template }}
          outputDir: ${{ env.new-dir }}
          overwrite: true
          skip: false
          cookiecutterValues: 
            '{
              // my values here
            }'

      - name: Replace new lines
        shell: bash
        run: |
          ls -la ${{ env.new-dir }}
          touch ${{ env.new-dir }}/new-file.txt
          ls -la ${{ env.new-dir }}
          
          VAR=`cat ${{ env.new-dir }}/main.tf`

          # replace new lines not allowed in output/input
          VAR=${VAR//'%0A'/$'\n'}
          VAR=${VAR//'%0D'/$'\r'}

          sudo echo "$VAR" > ${{ env.new-dir }}/main.tf
```

**Expected behavior**

* I expect to be able to edit the files created
* I expect the files created by cookiecutter to have the same permissions as files checked out or created by the github runner

**Actual behavior**

Files checked out by the runner or created by my bash script have the permissions
```
-rw-r--r--  1 runner docker    0 Aug  7 15:34 new-file.txt
```

Files created by cookiecutter have the permissions
```
-rw-r--r-- 1 root   root    240 Aug  7 15:34 main.tf
```

When I try to write to main.tf I get the error `Permission denied`

I also cannot change the owner on these files to the github runner - I am wondering if it's possible to do this in the dockerfile?

I am using the `ubuntu-22.04` github-hosted runner
